
services:
  movies-db:
    image: postgres:15
    container_name: movies-db
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - movies-db-data:/var/lib/postgresql/data

  games-db:
    image: postgres:15
    container_name: games-db
    environment:
      POSTGRES_DB: gamesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - games-db-data:/var/lib/postgresql/data

  books-db:
    image: postgres:15
    container_name: books-db
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - books-db-data:/var/lib/postgresql/data

  series-db:
    image: postgres:15
    container_name: series-db
    environment:
      POSTGRES_DB: seriesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - series-db-data:/var/lib/postgresql/data


  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  movies-db-data:
  games-db-data:
  books-db-data:
  series-db-data:
  auth-db-data:
