version: '3.8'

services:
  movies-db:
    image: postgres:15
    container_name: movies-db
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: moviesuser
      POSTGRES_PASSWORD: moviespass
    ports:
      - "5432:5432"
    volumes:
      - movies-db-data:/var/lib/postgresql/data

volumes:
  movies-db-data:
